/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbOrderItem implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer oritId;
    private final Integer oritOrderId;
    private final Integer oritProductId;
    private final Integer oritQuantity;
    private final BigDecimal oritPrice;
    private final String oritStatus;
    private final LocalDateTime oritCreatedAt;
    private final LocalDateTime updatedAt;

    public TbOrderItem(TbOrderItem value) {
        this.oritId = value.oritId;
        this.oritOrderId = value.oritOrderId;
        this.oritProductId = value.oritProductId;
        this.oritQuantity = value.oritQuantity;
        this.oritPrice = value.oritPrice;
        this.oritStatus = value.oritStatus;
        this.oritCreatedAt = value.oritCreatedAt;
        this.updatedAt = value.updatedAt;
    }

    public TbOrderItem(
        Integer oritId,
        Integer oritOrderId,
        Integer oritProductId,
        Integer oritQuantity,
        BigDecimal oritPrice,
        String oritStatus,
        LocalDateTime oritCreatedAt,
        LocalDateTime updatedAt
    ) {
        this.oritId = oritId;
        this.oritOrderId = oritOrderId;
        this.oritProductId = oritProductId;
        this.oritQuantity = oritQuantity;
        this.oritPrice = oritPrice;
        this.oritStatus = oritStatus;
        this.oritCreatedAt = oritCreatedAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_id</code>.
     */
    public Integer getOritId() {
        return this.oritId;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_order_id</code>.
     */
    public Integer getOritOrderId() {
        return this.oritOrderId;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_product_id</code>.
     */
    public Integer getOritProductId() {
        return this.oritProductId;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_quantity</code>.
     */
    public Integer getOritQuantity() {
        return this.oritQuantity;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_price</code>.
     */
    public BigDecimal getOritPrice() {
        return this.oritPrice;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_status</code>.
     */
    public String getOritStatus() {
        return this.oritStatus;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_created_at</code>.
     */
    public LocalDateTime getOritCreatedAt() {
        return this.oritCreatedAt;
    }

    /**
     * Getter for <code>public.tb_order_item.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbOrderItem other = (TbOrderItem) obj;
        if (this.oritId == null) {
            if (other.oritId != null)
                return false;
        }
        else if (!this.oritId.equals(other.oritId))
            return false;
        if (this.oritOrderId == null) {
            if (other.oritOrderId != null)
                return false;
        }
        else if (!this.oritOrderId.equals(other.oritOrderId))
            return false;
        if (this.oritProductId == null) {
            if (other.oritProductId != null)
                return false;
        }
        else if (!this.oritProductId.equals(other.oritProductId))
            return false;
        if (this.oritQuantity == null) {
            if (other.oritQuantity != null)
                return false;
        }
        else if (!this.oritQuantity.equals(other.oritQuantity))
            return false;
        if (this.oritPrice == null) {
            if (other.oritPrice != null)
                return false;
        }
        else if (!this.oritPrice.equals(other.oritPrice))
            return false;
        if (this.oritStatus == null) {
            if (other.oritStatus != null)
                return false;
        }
        else if (!this.oritStatus.equals(other.oritStatus))
            return false;
        if (this.oritCreatedAt == null) {
            if (other.oritCreatedAt != null)
                return false;
        }
        else if (!this.oritCreatedAt.equals(other.oritCreatedAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.oritId == null) ? 0 : this.oritId.hashCode());
        result = prime * result + ((this.oritOrderId == null) ? 0 : this.oritOrderId.hashCode());
        result = prime * result + ((this.oritProductId == null) ? 0 : this.oritProductId.hashCode());
        result = prime * result + ((this.oritQuantity == null) ? 0 : this.oritQuantity.hashCode());
        result = prime * result + ((this.oritPrice == null) ? 0 : this.oritPrice.hashCode());
        result = prime * result + ((this.oritStatus == null) ? 0 : this.oritStatus.hashCode());
        result = prime * result + ((this.oritCreatedAt == null) ? 0 : this.oritCreatedAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbOrderItem (");

        sb.append(oritId);
        sb.append(", ").append(oritOrderId);
        sb.append(", ").append(oritProductId);
        sb.append(", ").append(oritQuantity);
        sb.append(", ").append(oritPrice);
        sb.append(", ").append(oritStatus);
        sb.append(", ").append(oritCreatedAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
