/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer orderId;
    private final Integer orderCustomerId;
    private final LocalDateTime orderCreatedAt;
    private final String orderStatus;
    private final LocalDateTime updatedAt;

    public TbOrder(TbOrder value) {
        this.orderId = value.orderId;
        this.orderCustomerId = value.orderCustomerId;
        this.orderCreatedAt = value.orderCreatedAt;
        this.orderStatus = value.orderStatus;
        this.updatedAt = value.updatedAt;
    }

    public TbOrder(
        Integer orderId,
        Integer orderCustomerId,
        LocalDateTime orderCreatedAt,
        String orderStatus,
        LocalDateTime updatedAt
    ) {
        this.orderId = orderId;
        this.orderCustomerId = orderCustomerId;
        this.orderCreatedAt = orderCreatedAt;
        this.orderStatus = orderStatus;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.tb_order.order_id</code>.
     */
    public Integer getOrderId() {
        return this.orderId;
    }

    /**
     * Getter for <code>public.tb_order.order_customer_id</code>.
     */
    public Integer getOrderCustomerId() {
        return this.orderCustomerId;
    }

    /**
     * Getter for <code>public.tb_order.order_created_at</code>.
     */
    public LocalDateTime getOrderCreatedAt() {
        return this.orderCreatedAt;
    }

    /**
     * Getter for <code>public.tb_order.order_status</code>.
     */
    public String getOrderStatus() {
        return this.orderStatus;
    }

    /**
     * Getter for <code>public.tb_order.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbOrder other = (TbOrder) obj;
        if (this.orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!this.orderId.equals(other.orderId))
            return false;
        if (this.orderCustomerId == null) {
            if (other.orderCustomerId != null)
                return false;
        }
        else if (!this.orderCustomerId.equals(other.orderCustomerId))
            return false;
        if (this.orderCreatedAt == null) {
            if (other.orderCreatedAt != null)
                return false;
        }
        else if (!this.orderCreatedAt.equals(other.orderCreatedAt))
            return false;
        if (this.orderStatus == null) {
            if (other.orderStatus != null)
                return false;
        }
        else if (!this.orderStatus.equals(other.orderStatus))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.orderCustomerId == null) ? 0 : this.orderCustomerId.hashCode());
        result = prime * result + ((this.orderCreatedAt == null) ? 0 : this.orderCreatedAt.hashCode());
        result = prime * result + ((this.orderStatus == null) ? 0 : this.orderStatus.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbOrder (");

        sb.append(orderId);
        sb.append(", ").append(orderCustomerId);
        sb.append(", ").append(orderCreatedAt);
        sb.append(", ").append(orderStatus);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
