/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbProduct implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer productId;
    private final String productName;
    private final BigDecimal productPrice;
    private final LocalDateTime productCreatedAt;
    private final LocalDateTime updatedAt;

    public TbProduct(TbProduct value) {
        this.productId = value.productId;
        this.productName = value.productName;
        this.productPrice = value.productPrice;
        this.productCreatedAt = value.productCreatedAt;
        this.updatedAt = value.updatedAt;
    }

    public TbProduct(
        Integer productId,
        String productName,
        BigDecimal productPrice,
        LocalDateTime productCreatedAt,
        LocalDateTime updatedAt
    ) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productCreatedAt = productCreatedAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.tb_product.product_id</code>.
     */
    public Integer getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>public.tb_product.product_name</code>.
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Getter for <code>public.tb_product.product_price</code>.
     */
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }

    /**
     * Getter for <code>public.tb_product.product_created_at</code>.
     */
    public LocalDateTime getProductCreatedAt() {
        return this.productCreatedAt;
    }

    /**
     * Getter for <code>public.tb_product.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TbProduct other = (TbProduct) obj;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.productName == null) {
            if (other.productName != null)
                return false;
        }
        else if (!this.productName.equals(other.productName))
            return false;
        if (this.productPrice == null) {
            if (other.productPrice != null)
                return false;
        }
        else if (!this.productPrice.equals(other.productPrice))
            return false;
        if (this.productCreatedAt == null) {
            if (other.productCreatedAt != null)
                return false;
        }
        else if (!this.productCreatedAt.equals(other.productCreatedAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.productName == null) ? 0 : this.productName.hashCode());
        result = prime * result + ((this.productPrice == null) ? 0 : this.productPrice.hashCode());
        result = prime * result + ((this.productCreatedAt == null) ? 0 : this.productCreatedAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TbProduct (");

        sb.append(productId);
        sb.append(", ").append(productName);
        sb.append(", ").append(productPrice);
        sb.append(", ").append(productCreatedAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
