/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.example.jooq.Indexes;
import org.example.jooq.Keys;
import org.example.jooq.Public;
import org.example.jooq.tables.records.TbSchemaRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbSchema extends TableImpl<TbSchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tb_schema</code>
     */
    public static final TbSchema TB_SCHEMA = new TbSchema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbSchemaRecord> getRecordType() {
        return TbSchemaRecord.class;
    }

    /**
     * The column <code>public.tb_schema.installed_rank</code>.
     */
    public final TableField<TbSchemaRecord, Integer> INSTALLED_RANK = createField(DSL.name("installed_rank"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.tb_schema.version</code>.
     */
    public final TableField<TbSchemaRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.tb_schema.description</code>.
     */
    public final TableField<TbSchemaRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>public.tb_schema.type</code>.
     */
    public final TableField<TbSchemaRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.tb_schema.script</code>.
     */
    public final TableField<TbSchemaRecord, String> SCRIPT = createField(DSL.name("script"), SQLDataType.VARCHAR(1000).nullable(false), this, "");

    /**
     * The column <code>public.tb_schema.checksum</code>.
     */
    public final TableField<TbSchemaRecord, Integer> CHECKSUM = createField(DSL.name("checksum"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tb_schema.installed_by</code>.
     */
    public final TableField<TbSchemaRecord, String> INSTALLED_BY = createField(DSL.name("installed_by"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.tb_schema.installed_on</code>.
     */
    public final TableField<TbSchemaRecord, LocalDateTime> INSTALLED_ON = createField(DSL.name("installed_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.tb_schema.execution_time</code>.
     */
    public final TableField<TbSchemaRecord, Integer> EXECUTION_TIME = createField(DSL.name("execution_time"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.tb_schema.success</code>.
     */
    public final TableField<TbSchemaRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private TbSchema(Name alias, Table<TbSchemaRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbSchema(Name alias, Table<TbSchemaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tb_schema</code> table reference
     */
    public TbSchema(String alias) {
        this(DSL.name(alias), TB_SCHEMA);
    }

    /**
     * Create an aliased <code>public.tb_schema</code> table reference
     */
    public TbSchema(Name alias) {
        this(alias, TB_SCHEMA);
    }

    /**
     * Create a <code>public.tb_schema</code> table reference
     */
    public TbSchema() {
        this(DSL.name("tb_schema"), null);
    }

    public <O extends Record> TbSchema(Table<O> child, ForeignKey<O, TbSchemaRecord> key) {
        super(child, key, TB_SCHEMA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TB_SCHEMA_S_IDX);
    }

    @Override
    public UniqueKey<TbSchemaRecord> getPrimaryKey() {
        return Keys.TB_SCHEMA_PK;
    }

    @Override
    public TbSchema as(String alias) {
        return new TbSchema(DSL.name(alias), this);
    }

    @Override
    public TbSchema as(Name alias) {
        return new TbSchema(alias, this);
    }

    @Override
    public TbSchema as(Table<?> alias) {
        return new TbSchema(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbSchema rename(String name) {
        return new TbSchema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbSchema rename(Name name) {
        return new TbSchema(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbSchema rename(Table<?> name) {
        return new TbSchema(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super LocalDateTime, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Integer, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? super String, ? super LocalDateTime, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
