/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.example.jooq.tables.TbOrderItem;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbOrderItemRecord extends UpdatableRecordImpl<TbOrderItemRecord> implements Record8<Integer, Integer, Integer, Integer, BigDecimal, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_order_item.orit_id</code>.
     */
    public TbOrderItemRecord setOritId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_id</code>.
     */
    public Integer getOritId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_order_item.orit_order_id</code>.
     */
    public TbOrderItemRecord setOritOrderId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_order_id</code>.
     */
    public Integer getOritOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tb_order_item.orit_product_id</code>.
     */
    public TbOrderItemRecord setOritProductId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_product_id</code>.
     */
    public Integer getOritProductId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.tb_order_item.orit_quantity</code>.
     */
    public TbOrderItemRecord setOritQuantity(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_quantity</code>.
     */
    public Integer getOritQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tb_order_item.orit_price</code>.
     */
    public TbOrderItemRecord setOritPrice(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_price</code>.
     */
    public BigDecimal getOritPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.tb_order_item.orit_status</code>.
     */
    public TbOrderItemRecord setOritStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_status</code>.
     */
    public String getOritStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tb_order_item.orit_created_at</code>.
     */
    public TbOrderItemRecord setOritCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.orit_created_at</code>.
     */
    public LocalDateTime getOritCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.tb_order_item.updated_at</code>.
     */
    public TbOrderItemRecord setUpdatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_order_item.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, Integer, BigDecimal, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, Integer, BigDecimal, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbOrderItem.TB_ORDER_ITEM.ORIT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TbOrderItem.TB_ORDER_ITEM.ORIT_ORDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TbOrderItem.TB_ORDER_ITEM.ORIT_PRODUCT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return TbOrderItem.TB_ORDER_ITEM.ORIT_QUANTITY;
    }

    @Override
    public Field<BigDecimal> field5() {
        return TbOrderItem.TB_ORDER_ITEM.ORIT_PRICE;
    }

    @Override
    public Field<String> field6() {
        return TbOrderItem.TB_ORDER_ITEM.ORIT_STATUS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TbOrderItem.TB_ORDER_ITEM.ORIT_CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TbOrderItem.TB_ORDER_ITEM.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getOritId();
    }

    @Override
    public Integer component2() {
        return getOritOrderId();
    }

    @Override
    public Integer component3() {
        return getOritProductId();
    }

    @Override
    public Integer component4() {
        return getOritQuantity();
    }

    @Override
    public BigDecimal component5() {
        return getOritPrice();
    }

    @Override
    public String component6() {
        return getOritStatus();
    }

    @Override
    public LocalDateTime component7() {
        return getOritCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getOritId();
    }

    @Override
    public Integer value2() {
        return getOritOrderId();
    }

    @Override
    public Integer value3() {
        return getOritProductId();
    }

    @Override
    public Integer value4() {
        return getOritQuantity();
    }

    @Override
    public BigDecimal value5() {
        return getOritPrice();
    }

    @Override
    public String value6() {
        return getOritStatus();
    }

    @Override
    public LocalDateTime value7() {
        return getOritCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public TbOrderItemRecord value1(Integer value) {
        setOritId(value);
        return this;
    }

    @Override
    public TbOrderItemRecord value2(Integer value) {
        setOritOrderId(value);
        return this;
    }

    @Override
    public TbOrderItemRecord value3(Integer value) {
        setOritProductId(value);
        return this;
    }

    @Override
    public TbOrderItemRecord value4(Integer value) {
        setOritQuantity(value);
        return this;
    }

    @Override
    public TbOrderItemRecord value5(BigDecimal value) {
        setOritPrice(value);
        return this;
    }

    @Override
    public TbOrderItemRecord value6(String value) {
        setOritStatus(value);
        return this;
    }

    @Override
    public TbOrderItemRecord value7(LocalDateTime value) {
        setOritCreatedAt(value);
        return this;
    }

    @Override
    public TbOrderItemRecord value8(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TbOrderItemRecord values(Integer value1, Integer value2, Integer value3, Integer value4, BigDecimal value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbOrderItemRecord
     */
    public TbOrderItemRecord() {
        super(TbOrderItem.TB_ORDER_ITEM);
    }

    /**
     * Create a detached, initialised TbOrderItemRecord
     */
    public TbOrderItemRecord(Integer oritId, Integer oritOrderId, Integer oritProductId, Integer oritQuantity, BigDecimal oritPrice, String oritStatus, LocalDateTime oritCreatedAt, LocalDateTime updatedAt) {
        super(TbOrderItem.TB_ORDER_ITEM);

        setOritId(oritId);
        setOritOrderId(oritOrderId);
        setOritProductId(oritProductId);
        setOritQuantity(oritQuantity);
        setOritPrice(oritPrice);
        setOritStatus(oritStatus);
        setOritCreatedAt(oritCreatedAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised TbOrderItemRecord
     */
    public TbOrderItemRecord(org.example.jooq.tables.pojos.TbOrderItem value) {
        super(TbOrderItem.TB_ORDER_ITEM);

        if (value != null) {
            setOritId(value.getOritId());
            setOritOrderId(value.getOritOrderId());
            setOritProductId(value.getOritProductId());
            setOritQuantity(value.getOritQuantity());
            setOritPrice(value.getOritPrice());
            setOritStatus(value.getOritStatus());
            setOritCreatedAt(value.getOritCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
