/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.example.jooq.tables.TbProduct;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbProductRecord extends UpdatableRecordImpl<TbProductRecord> implements Record6<Integer, String, BigDecimal, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_product.product_id</code>.
     */
    public TbProductRecord setProductId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_product.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_product.product_name</code>.
     */
    public TbProductRecord setProductName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_product.product_name</code>.
     */
    public String getProductName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_product.product_price</code>.
     */
    public TbProductRecord setProductPrice(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_product.product_price</code>.
     */
    public BigDecimal getProductPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.tb_product.product_created_at</code>.
     */
    public TbProductRecord setProductCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_product.product_created_at</code>.
     */
    public LocalDateTime getProductCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.tb_product.updated_at</code>.
     */
    public TbProductRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_product.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.tb_product.product_status</code>.
     */
    public TbProductRecord setProductStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_product.product_status</code>.
     */
    public String getProductStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, BigDecimal, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, BigDecimal, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbProduct.TB_PRODUCT.PRODUCT_ID;
    }

    @Override
    public Field<String> field2() {
        return TbProduct.TB_PRODUCT.PRODUCT_NAME;
    }

    @Override
    public Field<BigDecimal> field3() {
        return TbProduct.TB_PRODUCT.PRODUCT_PRICE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TbProduct.TB_PRODUCT.PRODUCT_CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TbProduct.TB_PRODUCT.UPDATED_AT;
    }

    @Override
    public Field<String> field6() {
        return TbProduct.TB_PRODUCT.PRODUCT_STATUS;
    }

    @Override
    public Integer component1() {
        return getProductId();
    }

    @Override
    public String component2() {
        return getProductName();
    }

    @Override
    public BigDecimal component3() {
        return getProductPrice();
    }

    @Override
    public LocalDateTime component4() {
        return getProductCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public String component6() {
        return getProductStatus();
    }

    @Override
    public Integer value1() {
        return getProductId();
    }

    @Override
    public String value2() {
        return getProductName();
    }

    @Override
    public BigDecimal value3() {
        return getProductPrice();
    }

    @Override
    public LocalDateTime value4() {
        return getProductCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public String value6() {
        return getProductStatus();
    }

    @Override
    public TbProductRecord value1(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public TbProductRecord value2(String value) {
        setProductName(value);
        return this;
    }

    @Override
    public TbProductRecord value3(BigDecimal value) {
        setProductPrice(value);
        return this;
    }

    @Override
    public TbProductRecord value4(LocalDateTime value) {
        setProductCreatedAt(value);
        return this;
    }

    @Override
    public TbProductRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TbProductRecord value6(String value) {
        setProductStatus(value);
        return this;
    }

    @Override
    public TbProductRecord values(Integer value1, String value2, BigDecimal value3, LocalDateTime value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbProductRecord
     */
    public TbProductRecord() {
        super(TbProduct.TB_PRODUCT);
    }

    /**
     * Create a detached, initialised TbProductRecord
     */
    public TbProductRecord(Integer productId, String productName, BigDecimal productPrice, LocalDateTime productCreatedAt, LocalDateTime updatedAt, String productStatus) {
        super(TbProduct.TB_PRODUCT);

        setProductId(productId);
        setProductName(productName);
        setProductPrice(productPrice);
        setProductCreatedAt(productCreatedAt);
        setUpdatedAt(updatedAt);
        setProductStatus(productStatus);
    }

    /**
     * Create a detached, initialised TbProductRecord
     */
    public TbProductRecord(org.example.jooq.tables.pojos.TbProduct value) {
        super(TbProduct.TB_PRODUCT);

        if (value != null) {
            setProductId(value.getProductId());
            setProductName(value.getProductName());
            setProductPrice(value.getProductPrice());
            setProductCreatedAt(value.getProductCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setProductStatus(value.getProductStatus());
        }
    }
}
