/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.records;


import java.time.LocalDateTime;

import org.example.jooq.tables.TbSchema;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbSchemaRecord extends UpdatableRecordImpl<TbSchemaRecord> implements Record10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tb_schema.installed_rank</code>.
     */
    public TbSchemaRecord setInstalledRank(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.installed_rank</code>.
     */
    public Integer getInstalledRank() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tb_schema.version</code>.
     */
    public TbSchemaRecord setVersion(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.version</code>.
     */
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tb_schema.description</code>.
     */
    public TbSchemaRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tb_schema.type</code>.
     */
    public TbSchemaRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tb_schema.script</code>.
     */
    public TbSchemaRecord setScript(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.script</code>.
     */
    public String getScript() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tb_schema.checksum</code>.
     */
    public TbSchemaRecord setChecksum(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.checksum</code>.
     */
    public Integer getChecksum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tb_schema.installed_by</code>.
     */
    public TbSchemaRecord setInstalledBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.installed_by</code>.
     */
    public String getInstalledBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tb_schema.installed_on</code>.
     */
    public TbSchemaRecord setInstalledOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.installed_on</code>.
     */
    public LocalDateTime getInstalledOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.tb_schema.execution_time</code>.
     */
    public TbSchemaRecord setExecutionTime(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.execution_time</code>.
     */
    public Integer getExecutionTime() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tb_schema.success</code>.
     */
    public TbSchemaRecord setSuccess(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.tb_schema.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbSchema.TB_SCHEMA.INSTALLED_RANK;
    }

    @Override
    public Field<String> field2() {
        return TbSchema.TB_SCHEMA.VERSION;
    }

    @Override
    public Field<String> field3() {
        return TbSchema.TB_SCHEMA.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return TbSchema.TB_SCHEMA.TYPE;
    }

    @Override
    public Field<String> field5() {
        return TbSchema.TB_SCHEMA.SCRIPT;
    }

    @Override
    public Field<Integer> field6() {
        return TbSchema.TB_SCHEMA.CHECKSUM;
    }

    @Override
    public Field<String> field7() {
        return TbSchema.TB_SCHEMA.INSTALLED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TbSchema.TB_SCHEMA.INSTALLED_ON;
    }

    @Override
    public Field<Integer> field9() {
        return TbSchema.TB_SCHEMA.EXECUTION_TIME;
    }

    @Override
    public Field<Boolean> field10() {
        return TbSchema.TB_SCHEMA.SUCCESS;
    }

    @Override
    public Integer component1() {
        return getInstalledRank();
    }

    @Override
    public String component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getScript();
    }

    @Override
    public Integer component6() {
        return getChecksum();
    }

    @Override
    public String component7() {
        return getInstalledBy();
    }

    @Override
    public LocalDateTime component8() {
        return getInstalledOn();
    }

    @Override
    public Integer component9() {
        return getExecutionTime();
    }

    @Override
    public Boolean component10() {
        return getSuccess();
    }

    @Override
    public Integer value1() {
        return getInstalledRank();
    }

    @Override
    public String value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getScript();
    }

    @Override
    public Integer value6() {
        return getChecksum();
    }

    @Override
    public String value7() {
        return getInstalledBy();
    }

    @Override
    public LocalDateTime value8() {
        return getInstalledOn();
    }

    @Override
    public Integer value9() {
        return getExecutionTime();
    }

    @Override
    public Boolean value10() {
        return getSuccess();
    }

    @Override
    public TbSchemaRecord value1(Integer value) {
        setInstalledRank(value);
        return this;
    }

    @Override
    public TbSchemaRecord value2(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public TbSchemaRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TbSchemaRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public TbSchemaRecord value5(String value) {
        setScript(value);
        return this;
    }

    @Override
    public TbSchemaRecord value6(Integer value) {
        setChecksum(value);
        return this;
    }

    @Override
    public TbSchemaRecord value7(String value) {
        setInstalledBy(value);
        return this;
    }

    @Override
    public TbSchemaRecord value8(LocalDateTime value) {
        setInstalledOn(value);
        return this;
    }

    @Override
    public TbSchemaRecord value9(Integer value) {
        setExecutionTime(value);
        return this;
    }

    @Override
    public TbSchemaRecord value10(Boolean value) {
        setSuccess(value);
        return this;
    }

    @Override
    public TbSchemaRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, String value7, LocalDateTime value8, Integer value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbSchemaRecord
     */
    public TbSchemaRecord() {
        super(TbSchema.TB_SCHEMA);
    }

    /**
     * Create a detached, initialised TbSchemaRecord
     */
    public TbSchemaRecord(Integer installedRank, String version, String description, String type, String script, Integer checksum, String installedBy, LocalDateTime installedOn, Integer executionTime, Boolean success) {
        super(TbSchema.TB_SCHEMA);

        setInstalledRank(installedRank);
        setVersion(version);
        setDescription(description);
        setType(type);
        setScript(script);
        setChecksum(checksum);
        setInstalledBy(installedBy);
        setInstalledOn(installedOn);
        setExecutionTime(executionTime);
        setSuccess(success);
    }

    /**
     * Create a detached, initialised TbSchemaRecord
     */
    public TbSchemaRecord(org.example.jooq.tables.pojos.TbSchema value) {
        super(TbSchema.TB_SCHEMA);

        if (value != null) {
            setInstalledRank(value.getInstalledRank());
            setVersion(value.getVersion());
            setDescription(value.getDescription());
            setType(value.getType());
            setScript(value.getScript());
            setChecksum(value.getChecksum());
            setInstalledBy(value.getInstalledBy());
            setInstalledOn(value.getInstalledOn());
            setExecutionTime(value.getExecutionTime());
            setSuccess(value.getSuccess());
        }
    }
}
