/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.TbSchema;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TB_SCHEMA_S_IDX = Internal.createIndex(DSL.name("tb_schema_s_idx"), TbSchema.TB_SCHEMA, new OrderField[] { TbSchema.TB_SCHEMA.SUCCESS }, false);
}
