/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.TbSchema;
import org.example.jooq.tables.records.TbSchemaRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TbSchemaRecord> TB_SCHEMA_PK = Internal.createUniqueKey(TbSchema.TB_SCHEMA, DSL.name("tb_schema_pk"), new TableField[] { TbSchema.TB_SCHEMA.INSTALLED_RANK }, true);
}
