/*
 * This file is generated by jOOQ.
 */
package org.example.jooq;


import org.example.jooq.tables.TbOrder;
import org.example.jooq.tables.TbOrderItem;
import org.example.jooq.tables.TbProduct;
import org.example.jooq.tables.TbSchema;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.tb_order</code>.
     */
    public static final TbOrder TB_ORDER = TbOrder.TB_ORDER;

    /**
     * The table <code>public.tb_order_item</code>.
     */
    public static final TbOrderItem TB_ORDER_ITEM = TbOrderItem.TB_ORDER_ITEM;

    /**
     * The table <code>public.tb_product</code>.
     */
    public static final TbProduct TB_PRODUCT = TbProduct.TB_PRODUCT;

    /**
     * The table <code>public.tb_schema</code>.
     */
    public static final TbSchema TB_SCHEMA = TbSchema.TB_SCHEMA;
}
