/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.example.jooq.tables.TbSchema;
import org.example.jooq.tables.records.TbSchemaRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbSchemaDao extends DAOImpl<TbSchemaRecord, org.example.jooq.tables.pojos.TbSchema, Integer> {

    /**
     * Create a new TbSchemaDao without any configuration
     */
    public TbSchemaDao() {
        super(TbSchema.TB_SCHEMA, org.example.jooq.tables.pojos.TbSchema.class);
    }

    /**
     * Create a new TbSchemaDao with an attached configuration
     */
    public TbSchemaDao(Configuration configuration) {
        super(TbSchema.TB_SCHEMA, org.example.jooq.tables.pojos.TbSchema.class, configuration);
    }

    @Override
    public Integer getId(org.example.jooq.tables.pojos.TbSchema object) {
        return object.getInstalledRank();
    }

    /**
     * Fetch records that have <code>installed_rank BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfInstalledRank(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.INSTALLED_RANK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>installed_rank IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByInstalledRank(Integer... values) {
        return fetch(TbSchema.TB_SCHEMA.INSTALLED_RANK, values);
    }

    /**
     * Fetch a unique record that has <code>installed_rank = value</code>
     */
    public org.example.jooq.tables.pojos.TbSchema fetchOneByInstalledRank(Integer value) {
        return fetchOne(TbSchema.TB_SCHEMA.INSTALLED_RANK, value);
    }

    /**
     * Fetch a unique record that has <code>installed_rank = value</code>
     */
    public Optional<org.example.jooq.tables.pojos.TbSchema> fetchOptionalByInstalledRank(Integer value) {
        return fetchOptional(TbSchema.TB_SCHEMA.INSTALLED_RANK, value);
    }

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfVersion(String lowerInclusive, String upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.VERSION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByVersion(String... values) {
        return fetch(TbSchema.TB_SCHEMA.VERSION, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByDescription(String... values) {
        return fetch(TbSchema.TB_SCHEMA.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfType(String lowerInclusive, String upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByType(String... values) {
        return fetch(TbSchema.TB_SCHEMA.TYPE, values);
    }

    /**
     * Fetch records that have <code>script BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfScript(String lowerInclusive, String upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.SCRIPT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>script IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByScript(String... values) {
        return fetch(TbSchema.TB_SCHEMA.SCRIPT, values);
    }

    /**
     * Fetch records that have <code>checksum BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfChecksum(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.CHECKSUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>checksum IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByChecksum(Integer... values) {
        return fetch(TbSchema.TB_SCHEMA.CHECKSUM, values);
    }

    /**
     * Fetch records that have <code>installed_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfInstalledBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.INSTALLED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>installed_by IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByInstalledBy(String... values) {
        return fetch(TbSchema.TB_SCHEMA.INSTALLED_BY, values);
    }

    /**
     * Fetch records that have <code>installed_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfInstalledOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.INSTALLED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>installed_on IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByInstalledOn(LocalDateTime... values) {
        return fetch(TbSchema.TB_SCHEMA.INSTALLED_ON, values);
    }

    /**
     * Fetch records that have <code>execution_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfExecutionTime(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.EXECUTION_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>execution_time IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchByExecutionTime(Integer... values) {
        return fetch(TbSchema.TB_SCHEMA.EXECUTION_TIME, values);
    }

    /**
     * Fetch records that have <code>success BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchRangeOfSuccess(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(TbSchema.TB_SCHEMA.SUCCESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>success IN (values)</code>
     */
    public List<org.example.jooq.tables.pojos.TbSchema> fetchBySuccess(Boolean... values) {
        return fetch(TbSchema.TB_SCHEMA.SUCCESS, values);
    }
}
